server:
  port : 8084
spring:
  application:
    name : yc-redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: -1
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
